{
    'name': "Delete Account Journal Posted Entry",
    'version' : '14.1.1.1',
    'summary': 'Using this module you can Delete Account Journal Posted Entry in any stage of record from for view and list view, user wise.',
    'category': 'Accounting',
    'description': """ Using this module you can Delete Account Journal Posted Entry in any stage of record from for view and list view, user wise. """,
    "price": 10,
    'currency': 'EUR',
    "author" : "MAISOLUTIONSLLC",
    'sequence': 1,
    "email": 'apps@maisolutionsllc.com',
    "website":'http://maisolutionsllc.com/',
    'license': 'OPL-1',
    "depends" : ['base','account'],
	"data": [
		'security/account.xml',
		'views/account_view.xml',
	],
    'images': [],
    'qweb': [],
    'images': ['static/description/main_screenshot.png'],
    "live_test_url" : "https://youtu.be/c74wF9ctWIo ",
    'installable': True,
    'application': True,
    'auto_install': False,
}

